from .default import *
from .login import *
#from .blog import *
from .user import *
from .clinic import *
from .roles import *
from .wordcloud import *
from .spotify import *
from .qr import *
from .coursecatalog import *
from .project import *
from .survey import *
